#+title:      Multi-Perspective Project Proposal
#+date:       [2024-11-01 Fri 18:52]
#+filetags:   :edu101:
#+identifier: 20241101T185252

* Project Proposal

What role should artificial intelligence play in public schools?

** Three Perspectives

Inspired by David Labaree's [[denote:20241101T190235][Public Goods, Private Goods]]:

1. Democratic Equality
   None- schools need to teach students how to think.
   Furthermore, artificial intelligence is used in low-income school
   districts to account for lack of staffing, aggrivating class differences.
2. Social Efficiency
   Some- schools need to teach students how to work.
   In the near future, artificial intelligence will play a role in how students
   work across all fields. Students should feel comfortable using these tools
   before they enter the work force.
3. Social Mobility
   All- schools need students to be competitive after graduation.
   Restricting the methods of completing coursework reduces the efficiency of
   school as a credential. If the goal of parents and students to attend school
   is a degree, than nothing shall be witheld to get in the way of that.

** Some Sources
